### ISSUE TITLE
Pip install cvxpy fails with new version 1.0.1

### ISSUE THREAD

**Issue by kanayama-ACN** [cvxgrp/cvxpy#491]
Thank you for your great work on upgrading cvxpy 0.4.x -> 1.0.1, but the installation fails in my environment, while it has succeeded until yesterday (=before the upgrade.) Could you fix it?
```
pipenv install numpy
pipenv install cvxpy
=====
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Icvxpy/cvxcore/src/ -Icvxpy/cvxcore/python/ -Icvxpy/cvxcore/include/Eigen -I/home/XXXXXX/.local/share/virtualenvs/work-Dg4_eyG7/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c cvxpy/cvxcore/src/cvxcore.cpp -o build/temp.linux-x86_64-3.6/cvxpy/cvxcore/src/cvxcore.o
    cvxpy/cvxcore/src/cvxcore.cpp:15:23: fatal error: cvxcore.hpp: No such file or directory
     #include "cvxcore.hpp"
                           ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

```
It seems we need to add '-Icvxpy/cvxcore/src/' or so to let gcc find cvxcore.hpp. 
(Though I'm not sure why cvxcore.cpp cannot include cvxcore.hpp at the same directory.)

My Environment:
- CentOS 7 64bit as VirtualMachine on Windows 10.
- 2 GB RAM, 2 CPU for VM CentOS
- Python 3.6.5 with pipenv
- I also upgraded cmake 2.8.x (CentOS 7 yum default) -> 3.11.1 (today's latest) to install latest 'osqp'

----

In addition, I cannot install cvxcore with pip.
```
pip install cvxcore
====
Could not find a version that satisfies the requirement cvxcore (from versions: )
No matching distribution found for cvxcore
```
while GitHub page introduces above command. https://github.com/cvxgrp/cvxpy/tree/master/cvxpy/cvxcore

Note: cvxcore is not listed at pypi now.
https://pypi.org/simple/

**Comment by h3poteto** [comment]
Mee too.

**Comment by SteveDiamond** [comment]
@rileyjmurray your understanding is correct. I've edited the page and am working on a fix.

**Comment by kanayama-ACN** [comment]
Thank you for your quick fix. Improved, but still fails. Here is a log in my environment.
```
pipenv install numpy
pipenv install osqp
pipenv install cvxpy
====
...
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Icvxpy/cvxcore/src/ -Icvxpy/cvxcore/python/ -Icvxpy/cvxcore/include/Eigen -I/home/ec2-user/.local/share/virtualenvs/cvx-test-tPZW96Ot/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c cvxpy/cvxcore/src/cvxcore.cpp -o build/temp.linux-x86_64-3.6/cvxpy/cvxcore/src/cvxcore.o
    In file included from cvxpy/cvxcore/src/LinOp.hpp:21:0,
                     from cvxpy/cvxcore/src/cvxcore.hpp:19,
                     from cvxpy/cvxcore/src/cvxcore.cpp:15:
    cvxpy/cvxcore/src/Utils.hpp:20:35: fatal error: ../include/Eigen/Sparse: No such file or directory
     #include "../include/Eigen/Sparse"
```
(Sorry, I don't have the same machine (VM CentOS 7 64 bit on WIndows 10) with me now, so I tested with AWS EC2 & Amazon Linux (based on RedHat) 64 bit. cmake is 3.11.1.

**Comment by SteveDiamond** [comment]
Ok try again.

**Comment by cgohlke** [comment]
cvxpy-1.0.3 from PyPI works for me.

**Comment by SteveDiamond** [comment]
Excellent!

**Comment by kanayama-ACN** [comment]
It works now! thanks!

**Comment by czrcbl** [comment]
Hi,
I guess I am facing the same problem.
I am using linux deepin 15.7 and anaconda 5.2.0.
When I try `pip install cvxpy` I get the error:
```
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1
```
