### ISSUE TITLE
Issues with python builtins in CVXPY 1.0

### ISSUE THREAD

**Issue by sarahwie** [cvxgrp/cvxpy#446]
I've been working in a virtual environment with CVXPY manually installed from source from the `feature/dccp` branch. Upon switching to a manual install from the `1.0` branch in order to use OSQP as my solver, I'm getting some weird errors when trying to run the below snippet (which worked fine previously):

```
from cvxpy import *
import numpy as np

# Generate data
k = 300 
p = 300
n = 5000

np.random.seed(1)
D = np.random.rand(k, p)
# normalize D so that each column has L2 norm <= 1
for i in range(p):
    D[:, i] = D[:, i] / np.sqrt(np.sum(D[:, i]**2))

A = np.identity(min(p, n))
B = np.tile(A, int(np.ceil(n/p)))

```
```
Traceback (most recent call last):
  File "SC_test.py", line 22, in main
    A = np.identity(min(p, n))
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/atoms/min.py", line 28, in min
    return -max(-x, axis=axis)
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/atoms/max.py", line 31, in __init__
    super(max, self).__init__(x, axis=axis, keepdims=keepdims)
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/atoms/axis_atom.py", line 36, in __init__
    super(AxisAtom, self).__init__(expr)
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/atoms/atom.py", line 44, in __init__
    self.validate_arguments()
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/atoms/axis_atom.py", line 61, in validate_arguments
    raise ValueError("Invalid argument for axis.")
ValueError: Invalid argument for axis.
```
It essentially is throwing errors for any python builtins I'm using-- e.g. `min()` throws an error but `np.minimum()` does not, and the same for `sum()` but not for `np.sum()`.

Here is my system information:
```
cvxpy==1.0.0
cvxopt==1.1.9
numpy==1.13.3
scipy==1.0.0
CVXcanon uninstalled (caused errors)
```

Any suggestions on why this might be happening?

**Comment by sarahwie** [comment]
I uninstalled `CVXcanon` because of this error
```
Traceback (most recent call last):
  File "SC_test.py", line 1, in <module>
    from cvxpy import *
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/atoms/geo_mean.py", line 23, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/utilities/power_tools.py", line 21, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/atoms/affine/reshape.py", line 20, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/atoms/affine/affine_atom.py", line 25, in <module>
    from cvxpy.CVXcanon.python import canonInterface
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/CVXcanon/python/canonInterface.py", line 32, in <module>
    import cvxpy.CVXcanon.python.CVXcanon as CVXcanon
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/CVXcanon/python/CVXcanon.py", line 229, in <module>
    class LinOp(_object):
  File ".../lib/python2.7/site-packages/cvxpy-1.0.0-py2.7-linux-x86_64.egg/cvxpy/CVXcanon/python/CVXcanon.py", line 247, in LinOp
    __swig_setmethods__["data_ndim"] = _CVXcanon.LinOp_data_ndim_set
AttributeError: 'module' object has no attribute 'LinOp_data_ndim_set'
```
It's not installed by cvxpy 1.0 automatically as it is for other versions of cvxpy, so I thought this was fine.

**Comment by sarahwie** [comment]
Resolved. If you use `import *` from cvxpy, the new naming conventions in 1.0 override python builtin functions such as `sum()`, `min()`, and `max()`. So the options are to change the import call or otherwise not use python builtins.

**Comment by sarahwie** [comment]
This might be something worth refactoring, for ease of use.

**Comment by SteveDiamond** [comment]
Thanks for investigating this! I'm surprised DCCP still works with 1.0 actually. I hadn't refactored it yet. I'll update all the examples to the new ``import cvxpy as cv`` pattern.

**Comment by sarahwie** [comment]
@SteveDiamond No problem. I didn't actually use DCCP in 1.0 so I can't speak for that.
